### ISSUE TITLE
Fix rating average

### ISSUE THREAD

**Issue by gonzen2310** [PSUCoders/tutoring-hub#53] opened 2019-04-26 03:59 UTC
The rating average is not properly calculated when the user submits a new review

**Comment by MichaelGatesDev** [comment] 2019-04-26 16:46
The issue was caused by a typo which was used inconsistently across the devs (probably my fault for using the corrected version and confusing the app). Fixed with #54

**Closed** 2019-04-27 21:51 UTC
Labels: bug
